USE [master]
GO

/****** Object:  Database [Ratsada]    Script Date: 3/14/2017 10:23:13 AM ******/
CREATE DATABASE [Ratsada]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ratsada', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Ratsada.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Ratsada_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Ratsada_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Ratsada] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ratsada].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ratsada] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ratsada] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ratsada] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ratsada] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ratsada] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ratsada] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ratsada] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ratsada] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ratsada] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ratsada] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ratsada] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ratsada] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ratsada] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ratsada] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ratsada] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ratsada] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ratsada] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ratsada] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ratsada] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ratsada] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ratsada] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ratsada] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ratsada] SET RECOVERY FULL 
GO

ALTER DATABASE [Ratsada] SET  MULTI_USER 
GO

ALTER DATABASE [Ratsada] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ratsada] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ratsada] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ratsada] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Ratsada] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ratsada] SET  READ_WRITE 
GO

